import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

import{
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

import  {Loadermate} from "./loader";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});



export const metadata = {
  title: "Mock Interview Platform",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <ClerkProvider>
      <body
       className={inter.variable}
      >
        <Toaster/>
     
  {children}

      </body>
      </ClerkProvider>
    </html>
  );
}
